version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg_blog
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo_blog
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: neo4j_blog
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"   # Neo4j Browser (HTTP)
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data

volumes:
  pg_data:
  mongo_data:
  neo4j_data:
